abb_irb120:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Position Controllers ---------------------------------------
  joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: robot_joint_1
    pid: {p: 15000.0, i: 20.0, d: 100.0, i_clamp: 0.0, i_clamp_min: 0.0, i_clamp_max: 0.0}
  joint2_position_controller:
    type: effort_controllers/JointPositionController
    joint: robot_joint_2
    pid: {p: 6000.0, i: 10.0, d: 100.0, i_clamp: 0.0, i_clamp_min: 0.0, i_clamp_max: 0.0}
  joint3_position_controller:
    type: effort_controllers/JointPositionController
    joint: robot_joint_3
    pid: {p: 1000.0, i: 0.01, d: 50.0, i_clamp: 0.0, i_clamp_min: 0.0, i_clamp_max: 0.0}
  joint4_position_controller:
    type: effort_controllers/JointPositionController
    joint: robot_joint_4
    pid: {p: 1000.0, i: 0.0, d: 5.0, i_clamp: 0.0, i_clamp_min: 0.0, i_clamp_max: 0.0}
  joint5_position_controller:
    type: effort_controllers/JointPositionController
    joint: robot_joint_5
    pid: {p: 100.0, i: 0.0, d: 10.0, i_clamp: 0.0, i_clamp_min: 0.0, i_clamp_max: 0.0}
  joint6_position_controller:
    type: effort_controllers/JointPositionController
    joint: robot_joint_6
    pid: {p: 1.0, i: 0.0, d: 0.0, i_clamp: 0.0, i_clamp_min: 0.0, i_clamp_max: 0.0}
