controller_joint_names:
    - joint_1
    - joint_2
    - joint_3
    - joint_4
    - joint_5
    - joint_6

    # - r_gripper_joint
    # - r_gripper_l_finger_joint
    # - r_gripper_r_finger_joint
    # - r_gripper_l_finger_tip_joint
    # - r_gripper_r_finger_tip_joint
    # - r_gripper_motor_screw_joint
    # - r_gripper_motor_slider_joint
