controller_list:
  - name: ""
    action_ns: joint_trajectory_action
    type: FollowJointTrajectory
    joints: [joint_1, joint_2, joint_3, joint_4, joint_5, joint_6]

  - name: r_gripper_controller
    action_ns: gripper_action
    default: true
    joints:
      - r_gripper_joint
      - r_gripper_l_finger_joint
      - r_gripper_r_finger_joint
      - r_gripper_l_finger_tip_joint
      - r_gripper_r_finger_tip_joint
      - r_gripper_motor_screw_joint
      - r_gripper_motor_slider_joint


