controller_list:
  - name: fake_abb_arm_controller
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
  - name: fake_pr2_gripper_controller
    joints:
      - r_gripper_l_finger_joint
      - r_gripper_motor_slider_joint
      - r_gripper_motor_screw_joint
      - r_gripper_joint