controller_list:
  - name: fake_manipulator_controller
    joints:
      - robot_joint_1
      - robot_joint_2
      - robot_joint_3
      - robot_joint_4
      - robot_joint_5
      - robot_joint_6
  - name: fake_robotiq_controller
    joints:
      - robotiq_palm_finger_1_joint
      - robotiq_finger_1_joint_1
      - robotiq_finger_1_joint_2
      - robotiq_finger_1_joint_3
      - robotiq_finger_1_joint_paradistal_hinge
      - robotiq_finger_1_joint_median_actuating_hinge
      - robotiq_finger_1_joint_median_actuating_hinge_median_bar
      - robotiq_finger_1_joint_paramedian_hinge
      - robotiq_finger_1_joint_paramedian_hinge_median_bar_underactuated
      - robotiq_finger_1_joint_paraproximal_actuating_hinge
      - robotiq_finger_1_joint_paraproximal_bar
      - robotiq_finger_1_joint_proximal_actuating_hinge
      - robotiq_finger_1_joint_proximal_actuating_bar
      - robotiq_palm_finger_2_joint
      - robotiq_finger_2_joint_1
      - robotiq_finger_2_joint_2
      - robotiq_finger_2_joint_3
      - robotiq_finger_2_joint_paradistal_hinge
      - robotiq_finger_2_joint_median_actuating_hinge
      - robotiq_finger_2_joint_median_actuating_hinge_median_bar
      - robotiq_finger_2_joint_paramedian_hinge
      - robotiq_finger_2_joint_paramedian_hinge_median_bar_underactuated
      - robotiq_finger_2_joint_paraproximal_actuating_hinge
      - robotiq_finger_2_joint_paraproximal_bar
      - robotiq_finger_2_joint_proximal_actuating_hinge
      - robotiq_finger_2_joint_proximal_actuating_bar
      - robotiq_palm_finger_middle_joint
      - robotiq_finger_middle_joint_1
      - robotiq_finger_middle_joint_2
      - robotiq_finger_middle_joint_3
      - robotiq_finger_middle_joint_paradistal_hinge
      - robotiq_finger_middle_joint_median_actuating_hinge
      - robotiq_finger_middle_joint_median_actuating_hinge_median_bar
      - robotiq_finger_middle_joint_paramedian_hinge
      - robotiq_finger_middle_joint_paramedian_hinge_median_bar_underactuated
      - robotiq_finger_middle_joint_paraproximal_actuating_hinge
      - robotiq_finger_middle_joint_paraproximal_bar
      - robotiq_finger_middle_joint_proximal_actuating_hinge
      - robotiq_finger_middle_joint_proximal_actuating_bar