joint_limits:
  robotiq_finger_2_joint_paraproximal_actuating_hinge:
    has_velocity_limits: true
    max_velocity: 100
    has_acceleration_limits: false
    max_acceleration: 0
  robotiq_finger_middle_joint_paraproximal_actuating_hinge:
    has_velocity_limits: true
    max_velocity: 100
    has_acceleration_limits: false
    max_acceleration: 0
  robotiq_finger_middle_joint_paramedian_hinge_median_bar_underactuated:
    has_velocity_limits: true
    max_velocity: 100
    has_acceleration_limits: false
    max_acceleration: 0
  robotiq_finger_2_joint_proximal_actuating_bar:
    has_velocity_limits: true
    max_velocity: 100
    has_acceleration_limits: false
    max_acceleration: 0
  robotiq_finger_middle_joint_3:
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: false
    max_acceleration: 0
  robotiq_finger_middle_joint_median_actuating_hinge_median_bar:
    has_velocity_limits: true
    max_velocity: 100
    has_acceleration_limits: false
    max_acceleration: 0
  robotiq_finger_middle_joint_median_actuating_hinge:
    has_velocity_limits: true
    max_velocity: 100
    has_acceleration_limits: false
    max_acceleration: 0
  robotiq_finger_middle_joint_paramedian_hinge:
    has_velocity_limits: true
    max_velocity: 100
    has_acceleration_limits: false
    max_acceleration: 0
  robotiq_finger_2_joint_paradistal_hinge:
    has_velocity_limits: true
    max_velocity: 100
    has_acceleration_limits: false
    max_acceleration: 0
  robotiq_finger_middle_joint_paradistal_hinge:
    has_velocity_limits: true
    max_velocity: 100
    has_acceleration_limits: false
    max_acceleration: 0
  robot_joint_1:
    has_velocity_limits: true
    max_velocity: 4.36332
    has_acceleration_limits: false
    max_acceleration: 0
  robotiq_finger_2_joint_median_actuating_hinge_median_bar:
    has_velocity_limits: true
    max_velocity: 100
    has_acceleration_limits: false
    max_acceleration: 0
  robotiq_finger_middle_joint_proximal_actuating_bar:
    has_velocity_limits: true
    max_velocity: 100
    has_acceleration_limits: false
    max_acceleration: 0
  robot_joint_3:
    has_velocity_limits: true
    max_velocity: 4.36332
    has_acceleration_limits: false
    max_acceleration: 0
  robotiq_finger_1_joint_2:
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: false
    max_acceleration: 0
  robotiq_finger_2_joint_paramedian_hinge_median_bar_underactuated:
    has_velocity_limits: true
    max_velocity: 100
    has_acceleration_limits: false
    max_acceleration: 0
  robotiq_finger_2_joint_3:
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: false
    max_acceleration: 0
  robotiq_finger_middle_joint_2:
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: false
    max_acceleration: 0
  robotiq_finger_1_joint_1:
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: false
    max_acceleration: 0
  robotiq_finger_2_joint_proximal_actuating_hinge:
    has_velocity_limits: true
    max_velocity: 100
    has_acceleration_limits: false
    max_acceleration: 0
  robotiq_finger_1_joint_proximal_actuating_hinge:
    has_velocity_limits: true
    max_velocity: 100
    has_acceleration_limits: false
    max_acceleration: 0
  robotiq_finger_middle_joint_paraproximal_bar:
    has_velocity_limits: true
    max_velocity: 100
    has_acceleration_limits: false
    max_acceleration: 0
  robotiq_finger_1_joint_paraproximal_actuating_hinge:
    has_velocity_limits: true
    max_velocity: 100
    has_acceleration_limits: false
    max_acceleration: 0
  robotiq_finger_1_joint_3:
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: false
    max_acceleration: 0
  robotiq_finger_1_joint_paraproximal_bar:
    has_velocity_limits: true
    max_velocity: 100
    has_acceleration_limits: false
    max_acceleration: 0
  robot_joint_6:
    has_velocity_limits: true
    max_velocity: 7.33038
    has_acceleration_limits: false
    max_acceleration: 0
  robot_joint_4:
    has_velocity_limits: true
    max_velocity: 5.58505
    has_acceleration_limits: false
    max_acceleration: 0
  robotiq_finger_2_joint_2:
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: false
    max_acceleration: 0
  robotiq_finger_middle_joint_proximal_actuating_hinge:
    has_velocity_limits: true
    max_velocity: 100
    has_acceleration_limits: false
    max_acceleration: 0
  robotiq_palm_finger_2_joint:
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: false
    max_acceleration: 0
  robotiq_finger_1_joint_median_actuating_hinge:
    has_velocity_limits: true
    max_velocity: 100
    has_acceleration_limits: false
    max_acceleration: 0
  robotiq_finger_1_joint_paradistal_hinge:
    has_velocity_limits: true
    max_velocity: 100
    has_acceleration_limits: false
    max_acceleration: 0
  robotiq_finger_2_joint_median_actuating_hinge:
    has_velocity_limits: true
    max_velocity: 100
    has_acceleration_limits: false
    max_acceleration: 0
  robotiq_palm_finger_1_joint:
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: false
    max_acceleration: 0
  robotiq_finger_1_joint_paramedian_hinge:
    has_velocity_limits: true
    max_velocity: 100
    has_acceleration_limits: false
    max_acceleration: 0
  robotiq_finger_2_joint_1:
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: false
    max_acceleration: 0
  robot_joint_5:
    has_velocity_limits: true
    max_velocity: 5.58505
    has_acceleration_limits: false
    max_acceleration: 0
  robotiq_palm_finger_middle_joint:
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: false
    max_acceleration: 0
  robotiq_finger_2_joint_paraproximal_bar:
    has_velocity_limits: true
    max_velocity: 100
    has_acceleration_limits: false
    max_acceleration: 0
  robotiq_finger_2_joint_paramedian_hinge:
    has_velocity_limits: true
    max_velocity: 100
    has_acceleration_limits: false
    max_acceleration: 0
  robot_joint_2:
    has_velocity_limits: true
    max_velocity: 4.36332
    has_acceleration_limits: false
    max_acceleration: 0
  robotiq_finger_middle_joint_1:
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: false
    max_acceleration: 0
  robotiq_finger_1_joint_proximal_actuating_bar:
    has_velocity_limits: true
    max_velocity: 100
    has_acceleration_limits: false
    max_acceleration: 0
  robotiq_finger_1_joint_paramedian_hinge_median_bar_underactuated:
    has_velocity_limits: true
    max_velocity: 100
    has_acceleration_limits: false
    max_acceleration: 0
  robotiq_finger_1_joint_median_actuating_hinge_median_bar:
    has_velocity_limits: true
    max_velocity: 100
    has_acceleration_limits: false
    max_acceleration: 0